include rtl/ip/Makefile
include rtl/mac/Makefile
include rtl/hash_controller/Makefile
include rtl/tx/Makefile

RTL_PACKET_PARSER_SRC += $(RTL_IP_SRCS)
RTL_PACKET_PARSER_SRC += $(RTL_RX_MAC_SRCS)
RTL_PACKET_PARSER_SRC += $(RTL_HASH_CNTRL_SRCS)
RTL_PACKET_PARSER_SRC += $(RTL_TX_SRCS)