include rtl/Makefile

TOPLEVEL = packet_parser_top_tb
MODULE = testbenches.top.packet_parser_top_test

VERILOG_SOURCES += $(sort $(RTL_PACKET_PARSER_SRC))
VERILOG_SOURCES += testbenches/top/packet_parser_top_tb.sv