include rtl/rx/mac/pkg/Makefile

RTL_RX_MAC_IF_SRCS += $(wildcard rtl/rx/mac/if/rgmii_if.sv)
RTL_RX_MAC_IF_SRCS += $(wildcard rtl/rx/mac/if/gmii_if.sv)
RTL_RX_MAC_IF_SRCS += $(wildcard rtl/rx/mac/if/eth_fields_if.sv)
RTL_RX_MAC_IF_SRCS += $(wildcard rtl/rx/mac/if/eth_parser_error_if.sv)