include rtl/hash_controller/Makefile

TOPLEVEL = hash_controller_tb
MODULE = testbenches.hash_controller.hash_controller_tests

VERILOG_SOURCES += $(RTL_HASH_CNTRL_SRCS)
VERILOG_SOURCES += testbenches/hash_controller/hash_controller_tb.sv