include rtl/rx/mac/Makefile

TOPLEVEL = rx_mac_top_test
MODULE = testbenches.rx.mac.rx_mac_tests

# Use the correct variable defined in rtl/rx/mac/Makefile
VERILOG_SOURCES += $(RTL_RX_MAC_SRCS)
VERILOG_SOURCES += testbenches/rx/mac/rx_mac_top_test.sv