// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__pch.h"
#include "Vtop.h"
#include "Vtop___024root.h"
#include "Vtop_crc_pkg.h"
#include "Vtop_rgmii_if.h"
#include "Vtop_gmii_if.h"
#include "Vtop_mac_if_pkg.h"

// FUNCTIONS
Vtop__Syms::~Vtop__Syms()
{

    // Tear down scope hierarchy
    __Vhier.remove(0, &__Vscope_crc_pkg);
    __Vhier.remove(0, &__Vscope_mac_if_pkg);
    __Vhier.remove(0, &__Vscope_rx_mac_top_test);
    __Vhier.remove(&__Vscope_rx_mac_top_test, &__Vscope_rx_mac_top_test__rgmii_if_internal);
    __Vhier.remove(&__Vscope_rx_mac_top_test, &__Vscope_rx_mac_top_test__rx_mac_top_inst);
    __Vhier.remove(&__Vscope_rx_mac_top_test__rx_mac_top_inst, &__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst);
    __Vhier.remove(&__Vscope_rx_mac_top_test__rx_mac_top_inst, &__Vscope_rx_mac_top_test__rx_mac_top_inst__gmii_rx_if);
    __Vhier.remove(&__Vscope_rx_mac_top_test__rx_mac_top_inst, &__Vscope_rx_mac_top_test__rx_mac_top_inst__invalidate_packet_inst);
    __Vhier.remove(&__Vscope_rx_mac_top_test__rx_mac_top_inst, &__Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst);
    __Vhier.remove(&__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst, &__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1);
    __Vhier.remove(&__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1, &__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__0__KET__);
    __Vhier.remove(&__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1, &__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__1__KET__);
    __Vhier.remove(&__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1, &__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__2__KET__);
    __Vhier.remove(&__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1, &__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__3__KET__);
    __Vhier.remove(&__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1, &__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__iddr_sim_inst);
    __Vhier.remove(&__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__0__KET__, &__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__0__KET____iddr_sim_inst);
    __Vhier.remove(&__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__1__KET__, &__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__1__KET____iddr_sim_inst);
    __Vhier.remove(&__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__2__KET__, &__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__2__KET____iddr_sim_inst);
    __Vhier.remove(&__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__3__KET__, &__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__3__KET____iddr_sim_inst);
    __Vhier.remove(&__Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst, &__Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst);
    __Vhier.remove(&__Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst, &__Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst__data_pipeline_inst);
    __Vhier.remove(&__Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst, &__Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst__status_pipeline_inst);

}

Vtop__Syms::Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup module instances
    , TOP{this, namep}
    , TOP__crc_pkg{this, Verilated::catName(namep, "crc_pkg")}
    , TOP__mac_if_pkg{this, Verilated::catName(namep, "mac_if_pkg")}
    , TOP__rx_mac_top_test__DOT__rgmii_if_internal{this, Verilated::catName(namep, "rx_mac_top_test.rgmii_if_internal")}
    , TOP__rx_mac_top_test__DOT__rx_mac_top_inst__DOT__gmii_rx_if{this, Verilated::catName(namep, "rx_mac_top_test.rx_mac_top_inst.gmii_rx_if")}
{
        // Check resources
        Verilated::stackCheck(25);
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-9);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    TOP.__PVT__crc_pkg = &TOP__crc_pkg;
    TOP.__PVT__mac_if_pkg = &TOP__mac_if_pkg;
    TOP.__PVT__rx_mac_top_test__DOT__rgmii_if_internal = &TOP__rx_mac_top_test__DOT__rgmii_if_internal;
    TOP.__PVT__rx_mac_top_test__DOT__rx_mac_top_inst__DOT__gmii_rx_if = &TOP__rx_mac_top_test__DOT__rx_mac_top_inst__DOT__gmii_rx_if;
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    TOP__crc_pkg.__Vconfigure(true);
    TOP__mac_if_pkg.__Vconfigure(true);
    TOP__rx_mac_top_test__DOT__rgmii_if_internal.__Vconfigure(true);
    TOP__rx_mac_top_test__DOT__rx_mac_top_inst__DOT__gmii_rx_if.__Vconfigure(true);
    // Setup scopes
    __Vscope_TOP.configure(this, name(), "TOP", "TOP", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_crc_pkg.configure(this, name(), "crc_pkg", "crc_pkg", "crc_pkg", -9, VerilatedScope::SCOPE_PACKAGE);
    __Vscope_mac_if_pkg.configure(this, name(), "mac_if_pkg", "mac_if_pkg", "mac_if_pkg", -9, VerilatedScope::SCOPE_PACKAGE);
    __Vscope_rx_mac_top_test.configure(this, name(), "rx_mac_top_test", "rx_mac_top_test", "rx_mac_top_test", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_rx_mac_top_test__rgmii_if_internal.configure(this, name(), "rx_mac_top_test.rgmii_if_internal", "rgmii_if_internal", "rgmii_if", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_rx_mac_top_test__rx_mac_top_inst.configure(this, name(), "rx_mac_top_test.rx_mac_top_inst", "rx_mac_top_inst", "rx_mac_top", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst.configure(this, name(), "rx_mac_top_test.rx_mac_top_inst.ddr_sdr_converter_inst", "ddr_sdr_converter_inst", "ddr_sdr_converter", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1.configure(this, name(), "rx_mac_top_test.rx_mac_top_inst.ddr_sdr_converter_inst.genblk1", "genblk1", "<null>", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__0__KET__.configure(this, name(), "rx_mac_top_test.rx_mac_top_inst.ddr_sdr_converter_inst.genblk1.genblk1[0]", "genblk1[0]", "<null>", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__0__KET____iddr_sim_inst.configure(this, name(), "rx_mac_top_test.rx_mac_top_inst.ddr_sdr_converter_inst.genblk1.genblk1[0].iddr_sim_inst", "iddr_sim_inst", "iddr_sim", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__1__KET__.configure(this, name(), "rx_mac_top_test.rx_mac_top_inst.ddr_sdr_converter_inst.genblk1.genblk1[1]", "genblk1[1]", "<null>", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__1__KET____iddr_sim_inst.configure(this, name(), "rx_mac_top_test.rx_mac_top_inst.ddr_sdr_converter_inst.genblk1.genblk1[1].iddr_sim_inst", "iddr_sim_inst", "iddr_sim", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__2__KET__.configure(this, name(), "rx_mac_top_test.rx_mac_top_inst.ddr_sdr_converter_inst.genblk1.genblk1[2]", "genblk1[2]", "<null>", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__2__KET____iddr_sim_inst.configure(this, name(), "rx_mac_top_test.rx_mac_top_inst.ddr_sdr_converter_inst.genblk1.genblk1[2].iddr_sim_inst", "iddr_sim_inst", "iddr_sim", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__3__KET__.configure(this, name(), "rx_mac_top_test.rx_mac_top_inst.ddr_sdr_converter_inst.genblk1.genblk1[3]", "genblk1[3]", "<null>", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__3__KET____iddr_sim_inst.configure(this, name(), "rx_mac_top_test.rx_mac_top_inst.ddr_sdr_converter_inst.genblk1.genblk1[3].iddr_sim_inst", "iddr_sim_inst", "iddr_sim", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__iddr_sim_inst.configure(this, name(), "rx_mac_top_test.rx_mac_top_inst.ddr_sdr_converter_inst.genblk1.iddr_sim_inst", "iddr_sim_inst", "iddr_sim", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_rx_mac_top_test__rx_mac_top_inst__gmii_rx_if.configure(this, name(), "rx_mac_top_test.rx_mac_top_inst.gmii_rx_if", "gmii_rx_if", "gmii_if", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_rx_mac_top_test__rx_mac_top_inst__invalidate_packet_inst.configure(this, name(), "rx_mac_top_test.rx_mac_top_inst.invalidate_packet_inst", "invalidate_packet_inst", "invalidate_packet", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst.configure(this, name(), "rx_mac_top_test.rx_mac_top_inst.rx_crc_checker_inst", "rx_crc_checker_inst", "rx_crc_checker", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst.configure(this, name(), "rx_mac_top_test.rx_mac_top_inst.rx_crc_checker_inst.data_status_pipeline_inst", "data_status_pipeline_inst", "data_status_pipeline", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst__data_pipeline_inst.configure(this, name(), "rx_mac_top_test.rx_mac_top_inst.rx_crc_checker_inst.data_status_pipeline_inst.data_pipeline_inst", "data_pipeline_inst", "data_pipeline", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst__status_pipeline_inst.configure(this, name(), "rx_mac_top_test.rx_mac_top_inst.rx_crc_checker_inst.data_status_pipeline_inst.status_pipeline_inst", "status_pipeline_inst", "data_pipeline", -9, VerilatedScope::SCOPE_MODULE);

    // Set up scope hierarchy
    __Vhier.add(0, &__Vscope_crc_pkg);
    __Vhier.add(0, &__Vscope_mac_if_pkg);
    __Vhier.add(0, &__Vscope_rx_mac_top_test);
    __Vhier.add(&__Vscope_rx_mac_top_test, &__Vscope_rx_mac_top_test__rgmii_if_internal);
    __Vhier.add(&__Vscope_rx_mac_top_test, &__Vscope_rx_mac_top_test__rx_mac_top_inst);
    __Vhier.add(&__Vscope_rx_mac_top_test__rx_mac_top_inst, &__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst);
    __Vhier.add(&__Vscope_rx_mac_top_test__rx_mac_top_inst, &__Vscope_rx_mac_top_test__rx_mac_top_inst__gmii_rx_if);
    __Vhier.add(&__Vscope_rx_mac_top_test__rx_mac_top_inst, &__Vscope_rx_mac_top_test__rx_mac_top_inst__invalidate_packet_inst);
    __Vhier.add(&__Vscope_rx_mac_top_test__rx_mac_top_inst, &__Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst);
    __Vhier.add(&__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst, &__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1);
    __Vhier.add(&__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1, &__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__0__KET__);
    __Vhier.add(&__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1, &__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__1__KET__);
    __Vhier.add(&__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1, &__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__2__KET__);
    __Vhier.add(&__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1, &__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__3__KET__);
    __Vhier.add(&__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1, &__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__iddr_sim_inst);
    __Vhier.add(&__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__0__KET__, &__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__0__KET____iddr_sim_inst);
    __Vhier.add(&__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__1__KET__, &__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__1__KET____iddr_sim_inst);
    __Vhier.add(&__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__2__KET__, &__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__2__KET____iddr_sim_inst);
    __Vhier.add(&__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__3__KET__, &__Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__3__KET____iddr_sim_inst);
    __Vhier.add(&__Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst, &__Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst);
    __Vhier.add(&__Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst, &__Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst__data_pipeline_inst);
    __Vhier.add(&__Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst, &__Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst__status_pipeline_inst);

    // Setup export functions
    for (int __Vfinal = 0; __Vfinal < 2; ++__Vfinal) {
        __Vscope_TOP.varInsert(__Vfinal,"clk", &(TOP.clk), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"gmii_data_o", &(TOP.gmii_data_o), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_TOP.varInsert(__Vfinal,"gmii_data_valid_o", &(TOP.gmii_data_valid_o), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"invalid_frame_o", &(TOP.invalid_frame_o), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"rgmii_rx_ctrl_i", &(TOP.rgmii_rx_ctrl_i), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"rgmii_rx_data_i", &(TOP.rgmii_rx_data_i), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"rst", &(TOP.rst), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_crc_pkg.varInsert(__Vfinal,"CRC_POLY", const_cast<void*>(static_cast<const void*>(&(TOP__crc_pkg.CRC_POLY))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_crc_pkg.varInsert(__Vfinal,"CRC_REG_INITIAL_VALUE", const_cast<void*>(static_cast<const void*>(&(TOP__crc_pkg.CRC_REG_INITIAL_VALUE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_crc_pkg.varInsert(__Vfinal,"CRC_W", const_cast<void*>(static_cast<const void*>(&(TOP__crc_pkg.CRC_W))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_crc_pkg.varInsert(__Vfinal,"PARALLEL_CRC_POLY_8BIT", const_cast<void*>(static_cast<const void*>(&(TOP__crc_pkg.PARALLEL_CRC_POLY_8BIT))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mac_if_pkg.varInsert(__Vfinal,"GMII_DATA_W", const_cast<void*>(static_cast<const void*>(&(TOP__mac_if_pkg.GMII_DATA_W))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mac_if_pkg.varInsert(__Vfinal,"RGMII_DATA_W", const_cast<void*>(static_cast<const void*>(&(TOP__mac_if_pkg.RGMII_DATA_W))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_rx_mac_top_test.varInsert(__Vfinal,"clk", &(TOP.rx_mac_top_test__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test.varInsert(__Vfinal,"gmii_data_o", &(TOP.rx_mac_top_test__DOT__gmii_data_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_rx_mac_top_test.varInsert(__Vfinal,"gmii_data_valid_o", &(TOP.rx_mac_top_test__DOT__gmii_data_valid_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test.varInsert(__Vfinal,"invalid_frame_o", &(TOP.rx_mac_top_test__DOT__invalid_frame_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test.varInsert(__Vfinal,"rgmii_rx_ctrl_i", &(TOP.rx_mac_top_test__DOT__rgmii_rx_ctrl_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test.varInsert(__Vfinal,"rgmii_rx_data_i", &(TOP.rx_mac_top_test__DOT__rgmii_rx_data_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_rx_mac_top_test.varInsert(__Vfinal,"rst", &(TOP.rx_mac_top_test__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rgmii_if_internal.varInsert(__Vfinal,"ctrl", &(TOP__rx_mac_top_test__DOT__rgmii_if_internal.ctrl), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,0,0);
        __Vscope_rx_mac_top_test__rgmii_if_internal.varInsert(__Vfinal,"data", &(TOP__rx_mac_top_test__DOT__rgmii_if_internal.data), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst.varInsert(__Vfinal,"clk", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst.varInsert(__Vfinal,"crc_error", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__crc_error), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst.varInsert(__Vfinal,"crc_error_valid", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__crc_error_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst.varInsert(__Vfinal,"gmii_data_o", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__gmii_data_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst.varInsert(__Vfinal,"gmii_data_valid_o", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__gmii_data_valid_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst.varInsert(__Vfinal,"invalid_frame_o", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__invalid_frame_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst.varInsert(__Vfinal,"rst", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst.varInsert(__Vfinal,"TARGET", const_cast<void*>(static_cast<const void*>(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__TARGET.c_str())), true, VLVT_STRING,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst.varInsert(__Vfinal,"clk", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst.varInsert(__Vfinal,"rst", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__0__KET____iddr_sim_inst.varInsert(__Vfinal,"C", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__iddr_sim_inst__DOT__C), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__0__KET____iddr_sim_inst.varInsert(__Vfinal,"CE", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__iddr_sim_inst__DOT__CE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__0__KET____iddr_sim_inst.varInsert(__Vfinal,"D", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__iddr_sim_inst__DOT__D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__0__KET____iddr_sim_inst.varInsert(__Vfinal,"DDR_CLK_EDGE", const_cast<void*>(static_cast<const void*>(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__iddr_sim_inst__DOT__DDR_CLK_EDGE.c_str())), true, VLVT_STRING,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__0__KET____iddr_sim_inst.varInsert(__Vfinal,"INIT_Q1", const_cast<void*>(static_cast<const void*>(&(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__iddr_sim_inst__DOT__INIT_Q1))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__0__KET____iddr_sim_inst.varInsert(__Vfinal,"INIT_Q2", const_cast<void*>(static_cast<const void*>(&(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__iddr_sim_inst__DOT__INIT_Q2))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__0__KET____iddr_sim_inst.varInsert(__Vfinal,"Q1", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__iddr_sim_inst__DOT__Q1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__0__KET____iddr_sim_inst.varInsert(__Vfinal,"Q2", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__iddr_sim_inst__DOT__Q2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__0__KET____iddr_sim_inst.varInsert(__Vfinal,"R", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__iddr_sim_inst__DOT__R), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__0__KET____iddr_sim_inst.varInsert(__Vfinal,"RSTYPE", const_cast<void*>(static_cast<const void*>(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__iddr_sim_inst__DOT__RSTYPE.c_str())), true, VLVT_STRING,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__0__KET____iddr_sim_inst.varInsert(__Vfinal,"S", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__iddr_sim_inst__DOT__S), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__0__KET____iddr_sim_inst.varInsert(__Vfinal,"q1_2ff", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__iddr_sim_inst__DOT__q1_2ff), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__0__KET____iddr_sim_inst.varInsert(__Vfinal,"q1_ff", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__iddr_sim_inst__DOT__q1_ff), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__0__KET____iddr_sim_inst.varInsert(__Vfinal,"q2_2ff", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__iddr_sim_inst__DOT__q2_2ff), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__0__KET____iddr_sim_inst.varInsert(__Vfinal,"q2_ff", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__iddr_sim_inst__DOT__q2_ff), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__1__KET____iddr_sim_inst.varInsert(__Vfinal,"C", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__iddr_sim_inst__DOT__C), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__1__KET____iddr_sim_inst.varInsert(__Vfinal,"CE", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__iddr_sim_inst__DOT__CE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__1__KET____iddr_sim_inst.varInsert(__Vfinal,"D", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__iddr_sim_inst__DOT__D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__1__KET____iddr_sim_inst.varInsert(__Vfinal,"DDR_CLK_EDGE", const_cast<void*>(static_cast<const void*>(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__iddr_sim_inst__DOT__DDR_CLK_EDGE.c_str())), true, VLVT_STRING,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__1__KET____iddr_sim_inst.varInsert(__Vfinal,"INIT_Q1", const_cast<void*>(static_cast<const void*>(&(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__iddr_sim_inst__DOT__INIT_Q1))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__1__KET____iddr_sim_inst.varInsert(__Vfinal,"INIT_Q2", const_cast<void*>(static_cast<const void*>(&(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__iddr_sim_inst__DOT__INIT_Q2))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__1__KET____iddr_sim_inst.varInsert(__Vfinal,"Q1", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__iddr_sim_inst__DOT__Q1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__1__KET____iddr_sim_inst.varInsert(__Vfinal,"Q2", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__iddr_sim_inst__DOT__Q2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__1__KET____iddr_sim_inst.varInsert(__Vfinal,"R", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__iddr_sim_inst__DOT__R), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__1__KET____iddr_sim_inst.varInsert(__Vfinal,"RSTYPE", const_cast<void*>(static_cast<const void*>(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__iddr_sim_inst__DOT__RSTYPE.c_str())), true, VLVT_STRING,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__1__KET____iddr_sim_inst.varInsert(__Vfinal,"S", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__iddr_sim_inst__DOT__S), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__1__KET____iddr_sim_inst.varInsert(__Vfinal,"q1_2ff", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__iddr_sim_inst__DOT__q1_2ff), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__1__KET____iddr_sim_inst.varInsert(__Vfinal,"q1_ff", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__iddr_sim_inst__DOT__q1_ff), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__1__KET____iddr_sim_inst.varInsert(__Vfinal,"q2_2ff", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__iddr_sim_inst__DOT__q2_2ff), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__1__KET____iddr_sim_inst.varInsert(__Vfinal,"q2_ff", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__iddr_sim_inst__DOT__q2_ff), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__2__KET____iddr_sim_inst.varInsert(__Vfinal,"C", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__iddr_sim_inst__DOT__C), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__2__KET____iddr_sim_inst.varInsert(__Vfinal,"CE", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__iddr_sim_inst__DOT__CE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__2__KET____iddr_sim_inst.varInsert(__Vfinal,"D", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__iddr_sim_inst__DOT__D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__2__KET____iddr_sim_inst.varInsert(__Vfinal,"DDR_CLK_EDGE", const_cast<void*>(static_cast<const void*>(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__iddr_sim_inst__DOT__DDR_CLK_EDGE.c_str())), true, VLVT_STRING,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__2__KET____iddr_sim_inst.varInsert(__Vfinal,"INIT_Q1", const_cast<void*>(static_cast<const void*>(&(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__iddr_sim_inst__DOT__INIT_Q1))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__2__KET____iddr_sim_inst.varInsert(__Vfinal,"INIT_Q2", const_cast<void*>(static_cast<const void*>(&(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__iddr_sim_inst__DOT__INIT_Q2))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__2__KET____iddr_sim_inst.varInsert(__Vfinal,"Q1", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__iddr_sim_inst__DOT__Q1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__2__KET____iddr_sim_inst.varInsert(__Vfinal,"Q2", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__iddr_sim_inst__DOT__Q2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__2__KET____iddr_sim_inst.varInsert(__Vfinal,"R", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__iddr_sim_inst__DOT__R), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__2__KET____iddr_sim_inst.varInsert(__Vfinal,"RSTYPE", const_cast<void*>(static_cast<const void*>(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__iddr_sim_inst__DOT__RSTYPE.c_str())), true, VLVT_STRING,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__2__KET____iddr_sim_inst.varInsert(__Vfinal,"S", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__iddr_sim_inst__DOT__S), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__2__KET____iddr_sim_inst.varInsert(__Vfinal,"q1_2ff", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__iddr_sim_inst__DOT__q1_2ff), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__2__KET____iddr_sim_inst.varInsert(__Vfinal,"q1_ff", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__iddr_sim_inst__DOT__q1_ff), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__2__KET____iddr_sim_inst.varInsert(__Vfinal,"q2_2ff", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__iddr_sim_inst__DOT__q2_2ff), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__2__KET____iddr_sim_inst.varInsert(__Vfinal,"q2_ff", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__iddr_sim_inst__DOT__q2_ff), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__3__KET____iddr_sim_inst.varInsert(__Vfinal,"C", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__iddr_sim_inst__DOT__C), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__3__KET____iddr_sim_inst.varInsert(__Vfinal,"CE", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__iddr_sim_inst__DOT__CE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__3__KET____iddr_sim_inst.varInsert(__Vfinal,"D", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__iddr_sim_inst__DOT__D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__3__KET____iddr_sim_inst.varInsert(__Vfinal,"DDR_CLK_EDGE", const_cast<void*>(static_cast<const void*>(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__iddr_sim_inst__DOT__DDR_CLK_EDGE.c_str())), true, VLVT_STRING,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__3__KET____iddr_sim_inst.varInsert(__Vfinal,"INIT_Q1", const_cast<void*>(static_cast<const void*>(&(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__iddr_sim_inst__DOT__INIT_Q1))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__3__KET____iddr_sim_inst.varInsert(__Vfinal,"INIT_Q2", const_cast<void*>(static_cast<const void*>(&(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__iddr_sim_inst__DOT__INIT_Q2))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__3__KET____iddr_sim_inst.varInsert(__Vfinal,"Q1", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__iddr_sim_inst__DOT__Q1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__3__KET____iddr_sim_inst.varInsert(__Vfinal,"Q2", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__iddr_sim_inst__DOT__Q2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__3__KET____iddr_sim_inst.varInsert(__Vfinal,"R", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__iddr_sim_inst__DOT__R), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__3__KET____iddr_sim_inst.varInsert(__Vfinal,"RSTYPE", const_cast<void*>(static_cast<const void*>(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__iddr_sim_inst__DOT__RSTYPE.c_str())), true, VLVT_STRING,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__3__KET____iddr_sim_inst.varInsert(__Vfinal,"S", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__iddr_sim_inst__DOT__S), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__3__KET____iddr_sim_inst.varInsert(__Vfinal,"q1_2ff", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__iddr_sim_inst__DOT__q1_2ff), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__3__KET____iddr_sim_inst.varInsert(__Vfinal,"q1_ff", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__iddr_sim_inst__DOT__q1_ff), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__3__KET____iddr_sim_inst.varInsert(__Vfinal,"q2_2ff", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__iddr_sim_inst__DOT__q2_2ff), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__genblk1__BRA__3__KET____iddr_sim_inst.varInsert(__Vfinal,"q2_ff", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__iddr_sim_inst__DOT__q2_ff), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__iddr_sim_inst.varInsert(__Vfinal,"C", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__iddr_sim_inst__DOT__C), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__iddr_sim_inst.varInsert(__Vfinal,"CE", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__iddr_sim_inst__DOT__CE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__iddr_sim_inst.varInsert(__Vfinal,"D", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__iddr_sim_inst__DOT__D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__iddr_sim_inst.varInsert(__Vfinal,"DDR_CLK_EDGE", const_cast<void*>(static_cast<const void*>(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__iddr_sim_inst__DOT__DDR_CLK_EDGE.c_str())), true, VLVT_STRING,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__iddr_sim_inst.varInsert(__Vfinal,"INIT_Q1", const_cast<void*>(static_cast<const void*>(&(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__iddr_sim_inst__DOT__INIT_Q1))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__iddr_sim_inst.varInsert(__Vfinal,"INIT_Q2", const_cast<void*>(static_cast<const void*>(&(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__iddr_sim_inst__DOT__INIT_Q2))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__iddr_sim_inst.varInsert(__Vfinal,"Q1", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__iddr_sim_inst__DOT__Q1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__iddr_sim_inst.varInsert(__Vfinal,"Q2", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__iddr_sim_inst__DOT__Q2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__iddr_sim_inst.varInsert(__Vfinal,"R", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__iddr_sim_inst__DOT__R), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__iddr_sim_inst.varInsert(__Vfinal,"RSTYPE", const_cast<void*>(static_cast<const void*>(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__iddr_sim_inst__DOT__RSTYPE.c_str())), true, VLVT_STRING,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__iddr_sim_inst.varInsert(__Vfinal,"S", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__iddr_sim_inst__DOT__S), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__iddr_sim_inst.varInsert(__Vfinal,"q1_2ff", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__iddr_sim_inst__DOT__q1_2ff), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__iddr_sim_inst.varInsert(__Vfinal,"q1_ff", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__iddr_sim_inst__DOT__q1_ff), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__iddr_sim_inst.varInsert(__Vfinal,"q2_2ff", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__iddr_sim_inst__DOT__q2_2ff), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__ddr_sdr_converter_inst__genblk1__iddr_sim_inst.varInsert(__Vfinal,"q2_ff", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__iddr_sim_inst__DOT__q2_ff), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__gmii_rx_if.varInsert(__Vfinal,"data", &(TOP__rx_mac_top_test__DOT__rx_mac_top_inst__DOT__gmii_rx_if.data), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__gmii_rx_if.varInsert(__Vfinal,"error", &(TOP__rx_mac_top_test__DOT__rx_mac_top_inst__DOT__gmii_rx_if.error), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__gmii_rx_if.varInsert(__Vfinal,"valid", &(TOP__rx_mac_top_test__DOT__rx_mac_top_inst__DOT__gmii_rx_if.valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__invalidate_packet_inst.varInsert(__Vfinal,"clk", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__invalidate_packet_inst__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__invalidate_packet_inst.varInsert(__Vfinal,"crc_error", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__invalidate_packet_inst__DOT__crc_error), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__invalidate_packet_inst.varInsert(__Vfinal,"crc_error_valid", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__invalidate_packet_inst__DOT__crc_error_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__invalidate_packet_inst.varInsert(__Vfinal,"error", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__invalidate_packet_inst__DOT__error), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__invalidate_packet_inst.varInsert(__Vfinal,"error_pulse", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__invalidate_packet_inst__DOT__error_pulse), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__invalidate_packet_inst.varInsert(__Vfinal,"error_state_b", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__invalidate_packet_inst__DOT__error_state_b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__invalidate_packet_inst.varInsert(__Vfinal,"error_state_ff", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__invalidate_packet_inst__DOT__error_state_ff), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__invalidate_packet_inst.varInsert(__Vfinal,"rst", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__invalidate_packet_inst__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst.varInsert(__Vfinal,"PARALLEL_CRC_POLY", const_cast<void*>(static_cast<const void*>(&(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__PARALLEL_CRC_POLY))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst.varInsert(__Vfinal,"PIPELINE_DELAY", const_cast<void*>(static_cast<const void*>(&(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__PIPELINE_DELAY))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst.varInsert(__Vfinal,"clk", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst.varInsert(__Vfinal,"crc_checker_state_b", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__crc_checker_state_b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst.varInsert(__Vfinal,"crc_checker_state_ff", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__crc_checker_state_ff), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst.varInsert(__Vfinal,"crc_error", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__crc_error), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst.varInsert(__Vfinal,"crc_error_o", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__crc_error_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst.varInsert(__Vfinal,"crc_error_valid", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__crc_error_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst.varInsert(__Vfinal,"crc_error_valid_o", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__crc_error_valid_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst.varInsert(__Vfinal,"crc_shift_reg_b", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__crc_shift_reg_b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst.varInsert(__Vfinal,"crc_shift_reg_ff", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__crc_shift_reg_ff), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst.varInsert(__Vfinal,"rst", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst.varInsert(__Vfinal,"DATA_W", const_cast<void*>(static_cast<const void*>(&(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__DATA_W))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst.varInsert(__Vfinal,"PIPE_DEPTH", const_cast<void*>(static_cast<const void*>(&(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__PIPE_DEPTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst.varInsert(__Vfinal,"STATUS_W", const_cast<void*>(static_cast<const void*>(&(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__STATUS_W))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst.varInsert(__Vfinal,"clk", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst.varInsert(__Vfinal,"data_i", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__data_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst.varInsert(__Vfinal,"data_o", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__data_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst.varInsert(__Vfinal,"rst", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst.varInsert(__Vfinal,"status_i", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__status_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst.varInsert(__Vfinal,"status_o", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__status_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst__data_pipeline_inst.varInsert(__Vfinal,"DATA_W", const_cast<void*>(static_cast<const void*>(&(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__data_pipeline_inst__DOT__DATA_W))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst__data_pipeline_inst.varInsert(__Vfinal,"PIPE_DEPTH", const_cast<void*>(static_cast<const void*>(&(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__data_pipeline_inst__DOT__PIPE_DEPTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst__data_pipeline_inst.varInsert(__Vfinal,"RESET_EN", const_cast<void*>(static_cast<const void*>(&(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__data_pipeline_inst__DOT__RESET_EN))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst__data_pipeline_inst.varInsert(__Vfinal,"RESET_VALUE", const_cast<void*>(static_cast<const void*>(&(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__data_pipeline_inst__DOT__RESET_VALUE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst__data_pipeline_inst.varInsert(__Vfinal,"clk", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__data_pipeline_inst__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst__data_pipeline_inst.varInsert(__Vfinal,"data_i", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__data_pipeline_inst__DOT__data_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst__data_pipeline_inst.varInsert(__Vfinal,"data_o", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__data_pipeline_inst__DOT__data_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst__data_pipeline_inst.varInsert(__Vfinal,"data_shift_reg_ff", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__data_pipeline_inst__DOT__data_shift_reg_ff), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,-1 ,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst__data_pipeline_inst.varInsert(__Vfinal,"rst", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__data_pipeline_inst__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst__status_pipeline_inst.varInsert(__Vfinal,"DATA_W", const_cast<void*>(static_cast<const void*>(&(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__status_pipeline_inst__DOT__DATA_W))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst__status_pipeline_inst.varInsert(__Vfinal,"PIPE_DEPTH", const_cast<void*>(static_cast<const void*>(&(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__status_pipeline_inst__DOT__PIPE_DEPTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst__status_pipeline_inst.varInsert(__Vfinal,"RESET_EN", const_cast<void*>(static_cast<const void*>(&(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__status_pipeline_inst__DOT__RESET_EN))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst__status_pipeline_inst.varInsert(__Vfinal,"RESET_VALUE", const_cast<void*>(static_cast<const void*>(&(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__status_pipeline_inst__DOT__RESET_VALUE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst__status_pipeline_inst.varInsert(__Vfinal,"clk", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__status_pipeline_inst__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst__status_pipeline_inst.varInsert(__Vfinal,"data_i", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__status_pipeline_inst__DOT__data_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst__status_pipeline_inst.varInsert(__Vfinal,"data_o", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__status_pipeline_inst__DOT__data_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst__status_pipeline_inst.varInsert(__Vfinal,"data_shift_reg_ff", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__status_pipeline_inst__DOT__data_shift_reg_ff), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,-1 ,0,0);
        __Vscope_rx_mac_top_test__rx_mac_top_inst__rx_crc_checker_inst__data_status_pipeline_inst__status_pipeline_inst.varInsert(__Vfinal,"rst", &(TOP.rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__status_pipeline_inst__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
    }
}
