// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vtop.h for the primary calling header

#include "Vtop__pch.h"
#include "Vtop__Syms.h"
#include "Vtop___024root.h"

// Parameter definitions for Vtop___024root
constexpr CData/*0:0*/ Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__iddr_sim_inst__DOT__INIT_Q1;
constexpr CData/*0:0*/ Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__iddr_sim_inst__DOT__INIT_Q2;
constexpr CData/*0:0*/ Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__iddr_sim_inst__DOT__INIT_Q1;
constexpr CData/*0:0*/ Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__iddr_sim_inst__DOT__INIT_Q2;
constexpr CData/*0:0*/ Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__iddr_sim_inst__DOT__INIT_Q1;
constexpr CData/*0:0*/ Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__iddr_sim_inst__DOT__INIT_Q2;
constexpr CData/*0:0*/ Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__iddr_sim_inst__DOT__INIT_Q1;
constexpr CData/*0:0*/ Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__iddr_sim_inst__DOT__INIT_Q2;
constexpr CData/*0:0*/ Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__iddr_sim_inst__DOT__INIT_Q1;
constexpr CData/*0:0*/ Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__iddr_sim_inst__DOT__INIT_Q2;
constexpr CData/*0:0*/ Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__data_pipeline_inst__DOT__RESET_EN;
constexpr CData/*0:0*/ Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__status_pipeline_inst__DOT__RESET_EN;
constexpr IData/*31:0*/ Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__PARALLEL_CRC_POLY;
constexpr IData/*31:0*/ Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__PIPELINE_DELAY;
constexpr IData/*31:0*/ Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__DATA_W;
constexpr IData/*31:0*/ Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__STATUS_W;
constexpr IData/*31:0*/ Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__PIPE_DEPTH;
constexpr IData/*31:0*/ Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__data_pipeline_inst__DOT__DATA_W;
constexpr IData/*31:0*/ Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__data_pipeline_inst__DOT__PIPE_DEPTH;
constexpr IData/*31:0*/ Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__data_pipeline_inst__DOT__RESET_VALUE;
constexpr IData/*31:0*/ Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__status_pipeline_inst__DOT__DATA_W;
constexpr IData/*31:0*/ Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__status_pipeline_inst__DOT__PIPE_DEPTH;
constexpr IData/*31:0*/ Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__rx_crc_checker_inst__DOT__data_status_pipeline_inst__DOT__status_pipeline_inst__DOT__RESET_VALUE;
const std::string Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__TARGET = "SIM";
const std::string Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__iddr_sim_inst__DOT__DDR_CLK_EDGE = "SAME_EDGE_PIPELINED";
const std::string Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__iddr_sim_inst__DOT__RSTYPE = "SYNC";
const std::string Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__iddr_sim_inst__DOT__DDR_CLK_EDGE = "SAME_EDGE_PIPELINED";
const std::string Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__iddr_sim_inst__DOT__RSTYPE = "SYNC";
const std::string Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__iddr_sim_inst__DOT__DDR_CLK_EDGE = "SAME_EDGE_PIPELINED";
const std::string Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__iddr_sim_inst__DOT__RSTYPE = "SYNC";
const std::string Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__iddr_sim_inst__DOT__DDR_CLK_EDGE = "SAME_EDGE_PIPELINED";
const std::string Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__iddr_sim_inst__DOT__RSTYPE = "SYNC";
const std::string Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__iddr_sim_inst__DOT__DDR_CLK_EDGE = "SAME_EDGE_PIPELINED";
const std::string Vtop___024root::rx_mac_top_test__DOT__rx_mac_top_inst__DOT__ddr_sdr_converter_inst__DOT__genblk1__DOT__iddr_sim_inst__DOT__RSTYPE = "SYNC";


void Vtop___024root___ctor_var_reset(Vtop___024root* vlSelf);

Vtop___024root::Vtop___024root(Vtop__Syms* symsp, const char* v__name)
    : VerilatedModule{v__name}
    , vlSymsp{symsp}
 {
    // Reset structure values
    Vtop___024root___ctor_var_reset(this);
}

void Vtop___024root::__Vconfigure(bool first) {
    (void)first;  // Prevent unused variable warning
}

Vtop___024root::~Vtop___024root() {
}
